spring:
  datasource:
    generate-unique-name: false
    name: tacocloud

  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
  sql:
    init:
      mode: always

#  security:
#    oauth2:
#      client:
#        registration:

  mongodb:
    embedded:
      version: "4.0.21"

logging:
  level.: DEBUG
