spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
  data:
    rest:
      base-path: /data-api
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
  sql:
    init:
      mode: always

  mongodb:
    embedded:
      version: "4.0.21"
  jms:
    template:
      default-destination: tacocloud.order.queue

logging:
  level.: DEBUG

config:
  param1: common
  param2: something
